# *********
# * metqc *
# *********

# List of files
list_files: "list_files.txt"

# Input directory Path to raw sequences
input_dir: "/work/IMC_binf/sbagheri/IMC_projects/metatranscriptomics/data"

# Output directory path for output files.
output_dir: "output"

#WHere  the snakemake folder is
path: "/bulk/IMCbinf_bulk/sbagheri/Projects_IMC/metatranscriptomics/analysis"

# Suffix for forward reads.
forward_read_suffix: "_1.fastq.gz"

# Suffix for reverse reads.
reverse_read_suffix: "_2.fastq.gz"


### Cutadapt parameters

# The number of cpu cores to use for cutadapt
num_cpus: 7

# Choose whether to run cutadapt
run_cutadapt: TRUE

# Adapters for cutadapt
fwd_adapter: CTGTCTCTTATACACATCT
rev_adapter: CTGTCTCTTATACACATCT


### Prinseq parameters
trimleft: 0
trimright: 0
trim_qual_left: 30
trim_qual_right: 30
trim_qual_window: 10
trim_qual_step : 2
trim_qual_type: "mean"
trim_qual_rule: "lt"
lc_method: "dust"
lc_threshold: 7

# Minimum length for reads
minlength: 60

# Maximum number of N bases allowed
maxn: 15

### BMtagger Parameters

# Choose whether to run bmtagger
run_bmtagger: TRUE

# Index for bmfilter (part of bmtagger), bitmask file
bmfilter_ref: "/bulk/IMCshared_bulk/shared/dbs/bmtaggerDB/hg19_rRNA_mito_Hsapiens_rna/hg19_rRNA_mito_Hsapiens_rna_reference.bitmask"

# Index for srprism (part of bmtagger)
srprism_ref: "/bulk/IMCshared_bulk/shared//dbs/bmtaggerDB/hg19_rRNA_mito_Hsapiens_rna/hg19_rRNA_mito_Hsapiens_rna_reference.srprism"


#***************
#** sortmerna **
#***************

threads: 8


#DBs
##sortmerna

ref1: "/work/IMC_binf/sbagheri/IMC_projects/metatranscriptomics/github/metatranscriptomics/utils/databases/sortmerna/silva-arc-16s-id95.fasta"
ref2: "/work/IMC_binf/sbagheri/IMC_projects/metatranscriptomics/github/metatranscriptomics/utils/databases/sortmerna/silva-arc-23s-id98.fasta"
ref3: "/work/IMC_binf/sbagheri/IMC_projects/metatranscriptomics/github/metatranscriptomics/utils/databases/sortmerna/silva-bac-16s-id90.fasta"
ref4: "/work/IMC_binf/sbagheri/IMC_projects/metatranscriptomics/github/metatranscriptomics/utils/databases/sortmerna/silva-bac-23s-id98.fasta"
ref5: "/work/IMC_binf/sbagheri/IMC_projects/metatranscriptomics/github/metatranscriptomics/utils/databases/sortmerna/silva-euk-18s-id95.fasta"
ref6: "/work/IMC_binf/sbagheri/IMC_projects/metatranscriptomics/github/metatranscriptomics/utils/databases/sortmerna/silva-euk-28s-id98.fasta"


#***************
#** metaphlan **
#****************

## Metaphlan bowtie2 database.
metaphlan_database: "utils/databases/metaphlan/"
sgb_to_gtdb_tsv_file: "utils/databases/metaphlan/mpa_vJan21_CHOCOPhlAnSGB_202103_SGB2GTDB.tsv"



#*****************
#** metannotate **
#*****************

# Location of nucleotide database
nuc_db: "/work/IMC_binf/sbagheri/IMC_projects/metatranscriptomics/metannotate/dbs/dbs/chocophlan"

# Location os protein database
prot_db: "/work/IMC_binf/sbagheri/IMC_projects/metatranscriptomics/metannotate/dbs/dbs/uniref"

# Location of maping files

uniref90_name: "/work/IMC_binf/sbagheri/IMC_projects/metatranscriptomics/metannotate/dbs/dbs/utility_mapping/map_uniref90_name.txt.bz2"
eggnog_uniref90: "/work/IMC_binf/sbagheri/IMC_projects/metatranscriptomics/metannotate/dbs/dbs/utility_mapping/map_eggnog_uniref90.txt.gz"
ko_uniref90: "/work/IMC_binf/sbagheri/IMC_projects/metatranscriptomics/metannotate/dbs/dbs/utility_mapping/map_ko_uniref90.txt.gz"        
eggnog_name: "/work/IMC_binf/sbagheri/IMC_projects/metatranscriptomics/metannotate/dbs/dbs/utility_mapping/map_eggnog_name.txt.gz"      
ko_name: "/work/IMC_binf/sbagheri/IMC_projects/metatranscriptomics/metannotate/dbs/dbs/utility_mapping/map_ko_name.txt.gz"
uniref_name: "/work/IMC_binf/sbagheri/IMC_projects/metatranscriptomics/metannotate/dbs/dbs/utility_mapping/map_uniref90_name.txt.bz2"

